services:
    mysql:
        container_name: mysql_{{ project_name }}_container
        image: mariadb:10.6
        working_dir: /app
        command: 
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
        restart: always
        ports:
            - 58901:3306
        environment:
            - MYSQL_DATABASE=bakerydemo
            - MYSQL_ROOT_PASSWORD=bakerydemo
            - MYSQL_USER=bakerydemo
            - MYSQL_PASSWORD=bakerydemo
        volumes:
            - mysql_{{ project_name }}_volume:/var/lib/mysql

    redis:
        image: docker.io/redis:7
        container_name: redis_{{ project_name }}_container
        ports:
            - 55379:6379
        volumes:
            - redis_{{ project_name }}_volume:/data

volumes:
    mysql_{{ project_name }}_volume:
    redis_{{ project_name }}_volume: